spring:
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 100MB #最大请求文件的大小
      max-file-size: 20MB #设置单个文件最大长度
      file-size-threshold: 20MB #当文件达到多少时进行磁盘写入
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://59.110.213.213:3306/labwebsystem?useSSL=false&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: labwebsystem
    password: labwebsystem
    hikari:
      minimum-idle: 2

  resources:
    static-locations: classpath:static/,file:static/
  freemarker:
    suffix: .html
  jackson:
    date-format: yyyy-MM-dd
    time-zone: Hongkong
server:
  port: 8070



